//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteExpress
    {
        public ClienteExpress()
        {
            this.CuentaClienteExpress = new HashSet<CuentaClienteExpress>();
        }
    
        public long IdCliente { get; set; }
        public Nullable<int> Rut { get; set; }
        public string Dv { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<CuentaClienteExpress> CuentaClienteExpress { get; set; }
    }
}
