//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.CuentaCliente = new HashSet<CuentaCliente>();
            this.Grupo = new HashSet<Grupo>();
            this.IntentoCliente = new HashSet<IntentoCliente>();
        }
    
        public long IdCliente { get; set; }
        public Nullable<int> IdDireccion { get; set; }
        public int IdTermino { get; set; }
        public int Rut { get; set; }
        public string Dv { get; set; }
        public string Password { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public string EmailAlternativo { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public Nullable<int> IdGrupoEtario { get; set; }
        public Nullable<bool> RecibePromocion { get; set; }
        public Nullable<bool> RecibeCartola { get; set; }
        public string Sexo { get; set; }
        public string UrlImagenPerfil { get; set; }
    
        public virtual Direccion Direccion { get; set; }
        public virtual TerminoCondicion TerminoCondicion { get; set; }
        public virtual GrupoEtario GrupoEtario { get; set; }
        public virtual ICollection<CuentaCliente> CuentaCliente { get; set; }
        public virtual ICollection<Grupo> Grupo { get; set; }
        public virtual ICollection<IntentoCliente> IntentoCliente { get; set; }
    }
}
