//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public int IdConfiguracion { get; set; }
        public string NombreConfiguracion { get; set; }
        public string ValorConfiguracion { get; set; }
        public Nullable<bool> Encriptado { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
    }
}
