//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaBoleta
    {
        public ConsultaBoleta()
        {
            this.Cuenta = new HashSet<Cuenta>();
            this.ParametrosConsulta = new HashSet<ParametrosConsulta>();
            this.Pago = new HashSet<Pago>();
        }
    
        public long IdConsultaBoleta { get; set; }
        public long IdCliente { get; set; }
        public int IdEstadoBoleta { get; set; }
        public int IdTipoCliente { get; set; }
        public int MontoTotalConsulta { get; set; }
        public Nullable<bool> ConsultaNotificado { get; set; }
        public Nullable<System.DateTime> FechaConsulta { get; set; }
        public Nullable<bool> mobile { get; set; }
        public int IdCanal { get; set; }
        public Nullable<bool> Desplegada { get; set; }
    
        public virtual EstadoBoleta EstadoBoleta { get; set; }
        public virtual TipoCliente TipoCliente { get; set; }
        public virtual ICollection<Cuenta> Cuenta { get; set; }
        public virtual ICollection<ParametrosConsulta> ParametrosConsulta { get; set; }
        public virtual ICollection<Pago> Pago { get; set; }
    }
}
