//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaCliente
    {
        public CuentaCliente()
        {
            this.CuentaProcesoConsulta = new HashSet<CuentaProcesoConsulta>();
            this.IdentificadorCtaCli = new HashSet<IdentificadorCtaCli>();
        }
    
        public int IdCuentaCliente { get; set; }
        public long IdCliente { get; set; }
        public int IdEmpresaRubro { get; set; }
        public int IdGrupo { get; set; }
        public Nullable<System.DateTime> FechaInscripcion { get; set; }
        public string NombreCuentaCliente { get; set; }
        public Nullable<bool> ClienteRegistrado { get; set; }
        public Nullable<bool> clienteEliminado { get; set; }
        public Nullable<bool> CuentaHabilitada { get; set; }
        public Nullable<bool> CuentaValida { get; set; }
        public Nullable<bool> IgnoraCambio { get; set; }
        public Nullable<bool> CuentaEliminada { get; set; }
        public Nullable<int> CuentaClientePadre { get; set; }
        public Nullable<System.DateTime> UltimaFechaPago { get; set; }
        public Nullable<int> MontoUltimoPago { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual EmpresaRubro EmpresaRubro { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual ICollection<CuentaProcesoConsulta> CuentaProcesoConsulta { get; set; }
        public virtual ICollection<IdentificadorCtaCli> IdentificadorCtaCli { get; set; }
    }
}
