//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public Cuenta()
        {
            this.DetalleCuenta = new HashSet<DetalleCuenta>();
        }
    
        public long IdConsultaBoleta { get; set; }
        public int IdCuentaCliente { get; set; }
        public long IdCuenta { get; set; }
        public Nullable<long> MontoCuenta { get; set; }
        public Nullable<System.DateTime> FechaRespuestaConsulta { get; set; }
        public Nullable<int> codigo { get; set; }
        public string descripcion { get; set; }
        public Nullable<long> CuentaPadre { get; set; }
    
        public virtual ConsultaBoleta ConsultaBoleta { get; set; }
        public virtual ICollection<DetalleCuenta> DetalleCuenta { get; set; }
    }
}
