//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleResumenPago
    {
        public long IdPago { get; set; }
        public long IdPagoDetalle { get; set; }
        public long IdDetalleCuenta { get; set; }
        public long IdCuenta { get; set; }
        public string OrdenTienda { get; set; }
        public int IdEstadoPago { get; set; }
        public string DescripcionEstadoPago { get; set; }
        public int Monto { get; set; }
        public Nullable<int> NumCuotas { get; set; }
        public Nullable<int> Numtarjeta { get; set; }
        public string TbkCodAutorizacion { get; set; }
        public long IdCuentaCliente { get; set; }
        public string NombreCuentaCliente { get; set; }
        public System.DateTime FechaInsercion { get; set; }
        public int IdEmpresaRubro { get; set; }
        public string NombreEmpresaRubro { get; set; }
        public string Identificador { get; set; }
        public Nullable<long> TbkMontoCuota { get; set; }
        public Nullable<int> TbkCodRespuesta { get; set; }
    }
}
