//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoPago
    {
        public EstadoPago()
        {
            this.IntentoPago = new HashSet<IntentoPago>();
            this.Pago = new HashSet<Pago>();
            this.PagoDetalleBoleta = new HashSet<PagoDetalleBoleta>();
        }
    
        public int IdEstadoPago { get; set; }
        public string DescEstadoPago { get; set; }
    
        public virtual ICollection<IntentoPago> IntentoPago { get; set; }
        public virtual ICollection<Pago> Pago { get; set; }
        public virtual ICollection<PagoDetalleBoleta> PagoDetalleBoleta { get; set; }
    }
}
