//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormatoFechaEmpresaRubro
    {
        public long idFormatoFechaEmpresaRubro { get; set; }
        public Nullable<long> idEmpresaRubro { get; set; }
        public string formatofecha { get; set; }
    }
}
