//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Unired_HistoricaEntities : DbContext
    {
        public Unired_HistoricaEntities()
            : base("name=Unired_HistoricaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AbonoDinamico> AbonoDinamico { get; set; }
        public DbSet<AtributoImprimir> AtributoImprimir { get; set; }
        public DbSet<AtributoInformar> AtributoInformar { get; set; }
        public DbSet<AtributoNoLlave> AtributoNoLlave { get; set; }
        public DbSet<CampoOrdenConsulta> CampoOrdenConsulta { get; set; }
        public DbSet<Canal> Canal { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<ClienteExpress> ClienteExpress { get; set; }
        public DbSet<CodigoEmpresaImprimir> CodigoEmpresaImprimir { get; set; }
        public DbSet<CodigoEmpresaInformar> CodigoEmpresaInformar { get; set; }
        public DbSet<Comuna> Comuna { get; set; }
        public DbSet<ConfigMantenedorPopUp> ConfigMantenedorPopUp { get; set; }
        public DbSet<Configuracion> Configuracion { get; set; }
        public DbSet<ConfiguracionCanal> ConfiguracionCanal { get; set; }
        public DbSet<ConfiguracionProcesoConsulta> ConfiguracionProcesoConsulta { get; set; }
        public DbSet<ConfigVisualMantenedorPopUp> ConfigVisualMantenedorPopUp { get; set; }
        public DbSet<ConsultaBoleta> ConsultaBoleta { get; set; }
        public DbSet<Contacto> Contacto { get; set; }
        public DbSet<Cuenta> Cuenta { get; set; }
        public DbSet<CuentaCliente> CuentaCliente { get; set; }
        public DbSet<CuentaClienteExpress> CuentaClienteExpress { get; set; }
        public DbSet<CuentaConsultada> CuentaConsultada { get; set; }
        public DbSet<CuentaProcesoConsulta> CuentaProcesoConsulta { get; set; }
        public DbSet<CuerpoMail> CuerpoMail { get; set; }
        public DbSet<DetalleCuenta> DetalleCuenta { get; set; }
        public DbSet<DetalleResumenPago> DetalleResumenPago { get; set; }
        public DbSet<Direccion> Direccion { get; set; }
        public DbSet<Empresa> Empresa { get; set; }
        public DbSet<EmpresaRubro> EmpresaRubro { get; set; }
        public DbSet<EstadoBoleta> EstadoBoleta { get; set; }
        public DbSet<EstadoGeneral> EstadoGeneral { get; set; }
        public DbSet<EstadoImagen> EstadoImagen { get; set; }
        public DbSet<EstadoMail> EstadoMail { get; set; }
        public DbSet<EstadoNotificacion> EstadoNotificacion { get; set; }
        public DbSet<EstadoPago> EstadoPago { get; set; }
        public DbSet<Feriado> Feriado { get; set; }
        public DbSet<FormatoFechaEmpresaRubro> FormatoFechaEmpresaRubro { get; set; }
        public DbSet<Grupo> Grupo { get; set; }
        public DbSet<GrupoEtario> GrupoEtario { get; set; }
        public DbSet<Identificador> Identificador { get; set; }
        public DbSet<IdentificadorCtaCli> IdentificadorCtaCli { get; set; }
        public DbSet<IdentificadorCtaCliExpress> IdentificadorCtaCliExpress { get; set; }
        public DbSet<IdentificadorPublicidad> IdentificadorPublicidad { get; set; }
        public DbSet<ImagenesCorreo> ImagenesCorreo { get; set; }
        public DbSet<ImagenEstilo> ImagenEstilo { get; set; }
        public DbSet<IntentoCliente> IntentoCliente { get; set; }
        public DbSet<IntentoPago> IntentoPago { get; set; }
        public DbSet<IntentoUsuario> IntentoUsuario { get; set; }
        public DbSet<LinkAccesoPortal> LinkAccesoPortal { get; set; }
        public DbSet<Mailing> Mailing { get; set; }
        public DbSet<MantenedorImagenes> MantenedorImagenes { get; set; }
        public DbSet<MedioPago> MedioPago { get; set; }
        public DbSet<MultiIndustria> MultiIndustria { get; set; }
        public DbSet<Notificacion> Notificacion { get; set; }
        public DbSet<Pago> Pago { get; set; }
        public DbSet<PagoDetalleBoleta> PagoDetalleBoleta { get; set; }
        public DbSet<ParametrosConsulta> ParametrosConsulta { get; set; }
        public DbSet<PortalDisponible> PortalDisponible { get; set; }
        public DbSet<Profiles> Profiles { get; set; }
        public DbSet<Promociones> Promociones { get; set; }
        public DbSet<Provincia> Provincia { get; set; }
        public DbSet<Region> Region { get; set; }
        public DbSet<ReglaPresentacion> ReglaPresentacion { get; set; }
        public DbSet<RestriccionEPSCanal> RestriccionEPSCanal { get; set; }
        public DbSet<ResumenPago> ResumenPago { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Rubro> Rubro { get; set; }
        public DbSet<ServiciosProceso> ServiciosProceso { get; set; }
        public DbSet<Sucursal> Sucursal { get; set; }
        public DbSet<TerminoCondicion> TerminoCondicion { get; set; }
        public DbSet<Tipo_MedioPago> Tipo_MedioPago { get; set; }
        public DbSet<TipoAbono> TipoAbono { get; set; }
        public DbSet<TipoCartera> TipoCartera { get; set; }
        public DbSet<TipoCliente> TipoCliente { get; set; }
        public DbSet<TipoMail> TipoMail { get; set; }
        public DbSet<TipoMetaDato> TipoMetaDato { get; set; }
        public DbSet<Turno> Turno { get; set; }
        public DbSet<URLPermitidaCanal> URLPermitidaCanal { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Zona> Zona { get; set; }
    }
}
