//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentificadorPublicidad
    {
        public IdentificadorPublicidad()
        {
            this.MantenedorImagenes = new HashSet<MantenedorImagenes>();
        }
    
        public int IdPublicidad { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<MantenedorImagenes> MantenedorImagenes { get; set; }
    }
}
