//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenesCorreo
    {
        public int IdImagenesCorreo { get; set; }
        public string NombreImagen { get; set; }
        public string Link { get; set; }
        public byte[] binario { get; set; }
        public int Posicion { get; set; }
    }
}
