//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenEstilo
    {
        public ImagenEstilo()
        {
            this.Grupo = new HashSet<Grupo>();
        }
    
        public int IdImagen { get; set; }
        public int IdEstadoImagen { get; set; }
        public string UrlImagen { get; set; }
    
        public virtual EstadoImagen EstadoImagen { get; set; }
        public virtual ICollection<Grupo> Grupo { get; set; }
    }
}
