//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntentoPago
    {
        public long IdIntentoPago { get; set; }
        public int IdEstadoPago { get; set; }
        public int IdMedioPago { get; set; }
        public Nullable<System.DateTime> FechaIntentoPago { get; set; }
        public Nullable<long> IdPago { get; set; }
        public Nullable<System.DateTime> FechaRespuestaMP { get; set; }
        public Nullable<int> IdtipoMedioPago { get; set; }
    
        public virtual EstadoPago EstadoPago { get; set; }
        public virtual MedioPago MedioPago { get; set; }
        public virtual Pago Pago { get; set; }
    }
}
