//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailingHistorico
    {
        public int id_mail { get; set; }
        public int id_tipo_mail { get; set; }
        public string mail_to { get; set; }
        public System.DateTime fecha_solicitud { get; set; }
        public Nullable<int> id_agente_mail { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public short id_estado_mail { get; set; }
        public string mail_llave_externa { get; set; }
        public Nullable<int> retorno_server_mail { get; set; }
    }
}
