//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MailingEntities : DbContext
    {
        public MailingEntities()
            : base("name=MailingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Mailing> Mailing { get; set; }
    
        public virtual int proc_mail_confirmar(string psAgenteMail, Nullable<int> piIdMail, Nullable<int> piRetServerMail)
        {
            var psAgenteMailParameter = psAgenteMail != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psAgenteMail", psAgenteMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psAgenteMail", typeof(string));
    
            var piIdMailParameter = piIdMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", piIdMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", typeof(int));
    
            var piRetServerMailParameter = piRetServerMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piRetServerMail", piRetServerMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piRetServerMail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_mail_confirmar", psAgenteMailParameter, piIdMailParameter, piRetServerMailParameter);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<proc_mail_ConsultaPago_Result> proc_mail_ConsultaPago(Nullable<int> piIdCuenta, Nullable<int> piIdTipoMail)
        {
            var piIdCuentaParameter = piIdCuenta.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdCuenta", piIdCuenta) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdCuenta", typeof(int));
    
            var piIdTipoMailParameter = piIdTipoMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", piIdTipoMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_mail_ConsultaPago_Result>("proc_mail_ConsultaPago", piIdCuentaParameter, piIdTipoMailParameter);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<proc_mail_ConsultaPagoGeneral_Result> proc_mail_ConsultaPagoGeneral(Nullable<long> piIdPago, Nullable<int> piIdTipoMail)
        {
            var piIdPagoParameter = piIdPago.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdPago", piIdPago) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdPago", typeof(long));
    
            var piIdTipoMailParameter = piIdTipoMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", piIdTipoMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_mail_ConsultaPagoGeneral_Result>("proc_mail_ConsultaPagoGeneral", piIdPagoParameter, piIdTipoMailParameter);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<proc_mail_ConsultaPagoGeneralNR_Result> proc_mail_ConsultaPagoGeneralNR(Nullable<long> piIdPago, Nullable<int> piIdTipoMail)
        {
            var piIdPagoParameter = piIdPago.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdPago", piIdPago) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdPago", typeof(long));
    
            var piIdTipoMailParameter = piIdTipoMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", piIdTipoMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_mail_ConsultaPagoGeneralNR_Result>("proc_mail_ConsultaPagoGeneralNR", piIdPagoParameter, piIdTipoMailParameter);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<proc_mail_ConsultaPagoNR_Result> proc_mail_ConsultaPagoNR(Nullable<long> piIdCuenta, Nullable<int> piIdTipoMail)
        {
            var piIdCuentaParameter = piIdCuenta.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdCuenta", piIdCuenta) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdCuenta", typeof(long));
    
            var piIdTipoMailParameter = piIdTipoMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", piIdTipoMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_mail_ConsultaPagoNR_Result>("proc_mail_ConsultaPagoNR", piIdCuentaParameter, piIdTipoMailParameter);
        }
    
        public virtual int proc_mail_enviar(Nullable<int> piIdTipoMail, string psMailTo, string psMailLlaveExterna)
        {
            var piIdTipoMailParameter = piIdTipoMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", piIdTipoMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", typeof(int));
    
            var psMailToParameter = psMailTo != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psMailTo", psMailTo) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psMailTo", typeof(string));
    
            var psMailLlaveExternaParameter = psMailLlaveExterna != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psMailLlaveExterna", psMailLlaveExterna) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psMailLlaveExterna", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_mail_enviar", piIdTipoMailParameter, psMailToParameter, psMailLlaveExternaParameter);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<proc_mail_html_Result> proc_mail_html(Nullable<int> piIdMail, string psMailTo)
        {
            var piIdMailParameter = piIdMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", piIdMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", typeof(int));
    
            var psMailToParameter = psMailTo != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psMailTo", psMailTo) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psMailTo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_mail_html_Result>("proc_mail_html", piIdMailParameter, psMailToParameter);
        }
    
        public virtual int proc_mail_leer(string psAgenteMail)
        {
            var psAgenteMailParameter = psAgenteMail != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psAgenteMail", psAgenteMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psAgenteMail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_mail_leer", psAgenteMailParameter);
        }
    
        public virtual int proc_mail_leer_encabezado(Nullable<int> piIdMail)
        {
            var piIdMailParameter = piIdMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", piIdMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_mail_leer_encabezado", piIdMailParameter);
        }

        public virtual int proc_mail_leer_parametro(Nullable<int> piIdTipoMail, Nullable<int> piIdParametro, System.Data.Entity.Core.Objects.ObjectParameter psValorParametro)
        {
            var piIdTipoMailParameter = piIdTipoMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", piIdTipoMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", typeof(int));
    
            var piIdParametroParameter = piIdParametro.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdParametro", piIdParametro) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdParametro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_mail_leer_parametro", piIdTipoMailParameter, piIdParametroParameter, psValorParametro);
        }
    
        public virtual int proc_mail_leer_tipo_00(string psLlaveExterna, Nullable<int> piIdTipoMail, Nullable<int> piIdMail)
        {
            var psLlaveExternaParameter = psLlaveExterna != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", psLlaveExterna) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", typeof(string));
    
            var piIdTipoMailParameter = piIdTipoMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", piIdTipoMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", typeof(int));
    
            var piIdMailParameter = piIdMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", piIdMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_mail_leer_tipo_00", psLlaveExternaParameter, piIdTipoMailParameter, piIdMailParameter);
        }
    
        public virtual int proc_mail_leer_tipo_01(string psLlaveExterna, Nullable<int> piIdTipoMail, Nullable<int> piIdMail)
        {
            var psLlaveExternaParameter = psLlaveExterna != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", psLlaveExterna) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", typeof(string));
    
            var piIdTipoMailParameter = piIdTipoMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", piIdTipoMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", typeof(int));
    
            var piIdMailParameter = piIdMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", piIdMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_mail_leer_tipo_01", psLlaveExternaParameter, piIdTipoMailParameter, piIdMailParameter);
        }
    
        public virtual int proc_mail_leer_tipo_02(string psLlaveExterna, Nullable<int> piIdTipoMail, Nullable<int> piIdMail)
        {
            var psLlaveExternaParameter = psLlaveExterna != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", psLlaveExterna) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", typeof(string));
    
            var piIdTipoMailParameter = piIdTipoMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", piIdTipoMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", typeof(int));
    
            var piIdMailParameter = piIdMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", piIdMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_mail_leer_tipo_02", psLlaveExternaParameter, piIdTipoMailParameter, piIdMailParameter);
        }
    
        public virtual int proc_mail_leer_tipo_03(string psLlaveExterna, Nullable<int> piIdTipoMail, Nullable<int> piIdMail)
        {
            var psLlaveExternaParameter = psLlaveExterna != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", psLlaveExterna) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", typeof(string));
    
            var piIdTipoMailParameter = piIdTipoMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", piIdTipoMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", typeof(int));
    
            var piIdMailParameter = piIdMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", piIdMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_mail_leer_tipo_03", psLlaveExternaParameter, piIdTipoMailParameter, piIdMailParameter);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<proc_mail_leer_tipo_06_Result> proc_mail_leer_tipo_06(string psLlaveExterna, Nullable<int> piIdTipoMail, Nullable<int> piIdMail)
        {
            var psLlaveExternaParameter = psLlaveExterna != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", psLlaveExterna) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", typeof(string));
    
            var piIdTipoMailParameter = piIdTipoMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", piIdTipoMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", typeof(int));
    
            var piIdMailParameter = piIdMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", piIdMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_mail_leer_tipo_06_Result>("proc_mail_leer_tipo_06", psLlaveExternaParameter, piIdTipoMailParameter, piIdMailParameter);
        }
    
        public virtual int proc_mail_leer_tipo_07(string psLlaveExterna, Nullable<int> piIdTipoMail, Nullable<int> piIdMail)
        {
            var psLlaveExternaParameter = psLlaveExterna != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", psLlaveExterna) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", typeof(string));
    
            var piIdTipoMailParameter = piIdTipoMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", piIdTipoMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", typeof(int));
    
            var piIdMailParameter = piIdMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", piIdMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_mail_leer_tipo_07", psLlaveExternaParameter, piIdTipoMailParameter, piIdMailParameter);
        }
    
        public virtual int proc_mail_leer_tipo_08(string psLlaveExterna, Nullable<int> piIdTipoMail, Nullable<int> piIdMail)
        {
            var psLlaveExternaParameter = psLlaveExterna != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", psLlaveExterna) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", typeof(string));
    
            var piIdTipoMailParameter = piIdTipoMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", piIdTipoMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", typeof(int));
    
            var piIdMailParameter = piIdMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", piIdMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_mail_leer_tipo_08", psLlaveExternaParameter, piIdTipoMailParameter, piIdMailParameter);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<proc_mail_leer_tipo_09_Result> proc_mail_leer_tipo_09(string psLlaveExterna, Nullable<int> piIdTipoMail, Nullable<int> piIdMail)
        {
            var psLlaveExternaParameter = psLlaveExterna != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", psLlaveExterna) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", typeof(string));
    
            var piIdTipoMailParameter = piIdTipoMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", piIdTipoMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", typeof(int));
    
            var piIdMailParameter = piIdMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", piIdMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_mail_leer_tipo_09_Result>("proc_mail_leer_tipo_09", psLlaveExternaParameter, piIdTipoMailParameter, piIdMailParameter);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<proc_mail_leer_tipo_10_Result> proc_mail_leer_tipo_10(string psLlaveExterna, Nullable<int> piIdTipoMail, Nullable<int> piIdMail)
        {
            var psLlaveExternaParameter = psLlaveExterna != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", psLlaveExterna) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", typeof(string));
    
            var piIdTipoMailParameter = piIdTipoMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", piIdTipoMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", typeof(int));
    
            var piIdMailParameter = piIdMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", piIdMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_mail_leer_tipo_10_Result>("proc_mail_leer_tipo_10", psLlaveExternaParameter, piIdTipoMailParameter, piIdMailParameter);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<proc_mail_leer_tipo_11_Result> proc_mail_leer_tipo_11(string psLlaveExterna, Nullable<int> piIdTipoMail, Nullable<int> piIdMail)
        {
            var psLlaveExternaParameter = psLlaveExterna != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", psLlaveExterna) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", typeof(string));
    
            var piIdTipoMailParameter = piIdTipoMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", piIdTipoMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", typeof(int));
    
            var piIdMailParameter = piIdMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", piIdMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_mail_leer_tipo_11_Result>("proc_mail_leer_tipo_11", psLlaveExternaParameter, piIdTipoMailParameter, piIdMailParameter);
        }
    
        public virtual int proc_mail_leer_tipo_12(string psLlaveExterna, Nullable<int> piIdTipoMail, Nullable<int> piIdMail)
        {
            var psLlaveExternaParameter = psLlaveExterna != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", psLlaveExterna) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psLlaveExterna", typeof(string));
    
            var piIdTipoMailParameter = piIdTipoMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", piIdTipoMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdTipoMail", typeof(int));
    
            var piIdMailParameter = piIdMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", piIdMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("piIdMail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_mail_leer_tipo_12", psLlaveExternaParameter, piIdTipoMailParameter, piIdMailParameter);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<proc_mail_leer1_Result> proc_mail_leer1(string psAgenteMail, Nullable<long> psIdMail)
        {
            var psAgenteMailParameter = psAgenteMail != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psAgenteMail", psAgenteMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psAgenteMail", typeof(string));
    
            var psIdMailParameter = psIdMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psIdMail", psIdMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psIdMail", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_mail_leer1_Result>("proc_mail_leer1", psAgenteMailParameter, psIdMailParameter);
        }

        public virtual int proc_mail_parser_var(string psMsg, string psTag, string psValor, System.Data.Entity.Core.Objects.ObjectParameter psMsgOut)
        {
            var psMsgParameter = psMsg != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psMsg", psMsg) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psMsg", typeof(string));
    
            var psTagParameter = psTag != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psTag", psTag) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psTag", typeof(string));
    
            var psValorParameter = psValor != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psValor", psValor) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psValor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_mail_parser_var", psMsgParameter, psTagParameter, psValorParameter, psMsgOut);
        }
    
        public virtual int proc_MarcaEnProceso(Nullable<int> idmailing)
        {
            var idmailingParameter = idmailing.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("idmailing", idmailing) :
                new System.Data.Entity.Core.Objects.ObjectParameter("idmailing", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_MarcaEnProceso", idmailingParameter);
        }
    
        public virtual int proc_MarcaRespuestaEnvio(Nullable<int> idmailing, Nullable<int> retorno)
        {
            var idmailingParameter = idmailing.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("idmailing", idmailing) :
                new System.Data.Entity.Core.Objects.ObjectParameter("idmailing", typeof(int));
    
            var retornoParameter = retorno.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("retorno", retorno) :
                new System.Data.Entity.Core.Objects.ObjectParameter("retorno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_MarcaRespuestaEnvio", idmailingParameter, retornoParameter);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<proc_ObtenerDatosMail_Result> proc_ObtenerDatosMail(Nullable<int> idMail)
        {
            var idMailParameter = idMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("IdMail", idMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("IdMail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ObtenerDatosMail_Result>("proc_ObtenerDatosMail", idMailParameter);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<Nullable<int>> proc_ObtenerHilos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("proc_ObtenerHilos");
        }
    
        public virtual int proc_ResetMail(Nullable<int> idmailing)
        {
            var idmailingParameter = idmailing.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("idmailing", idmailing) :
                new System.Data.Entity.Core.Objects.ObjectParameter("idmailing", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_ResetMail", idmailingParameter);
        }

        public virtual int procU_Reemplazar_Acentos(string psTx_Original, string tiene_acento, System.Data.Entity.Core.Objects.ObjectParameter psTx_OriginalOut)
        {
            var psTx_OriginalParameter = psTx_Original != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psTx_Original", psTx_Original) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psTx_Original", typeof(string));
    
            var tiene_acentoParameter = tiene_acento != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("tiene_acento", tiene_acento) :
                new System.Data.Entity.Core.Objects.ObjectParameter("tiene_acento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procU_Reemplazar_Acentos", psTx_OriginalParameter, tiene_acentoParameter, psTx_OriginalOut);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<proc_mail_ImagenesCorreo_Result> proc_mail_ImagenesCorreo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_mail_ImagenesCorreo_Result>("proc_mail_ImagenesCorreo");
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<proc_mail_leer_Efectivo_Result> proc_mail_leer_Efectivo(Nullable<int> psIdMail)
        {
            var psIdMailParameter = psIdMail.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("psIdMail", psIdMail) :
                new System.Data.Entity.Core.Objects.ObjectParameter("psIdMail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_mail_leer_Efectivo_Result>("proc_mail_leer_Efectivo", psIdMailParameter);
        }
    }
}
