//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MantenedorImagenes
    {
        public int idMantenedorImagenes { get; set; }
        public Nullable<int> IdPublicidad { get; set; }
        public string RutaImagen { get; set; }
        public string Link { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> Activa { get; set; }
        public string TARGET { get; set; }
        public byte[] binario { get; set; }
        public string Titulo { get; set; }
    
        public virtual IdentificadorPublicidad IdentificadorPublicidad { get; set; }
    }
}
