//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class UniredModelEntities : DbContext
    {
        public UniredModelEntities()
            : base("name=UniredModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Configuracion> Configuracion { get; set; }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<P_Portal_ComprobanteResumenPDF_Result> P_Portal_ComprobanteResumenPDF(Nullable<long> pi_IdPago, Nullable<long> pi_IdCuenta)
        {
            var pi_IdPagoParameter = pi_IdPago.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("Pi_IdPago", pi_IdPago) :
                new System.Data.Entity.Core.Objects.ObjectParameter("Pi_IdPago", typeof(long));
    
            var pi_IdCuentaParameter = pi_IdCuenta.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("Pi_IdCuenta", pi_IdCuenta) :
                new System.Data.Entity.Core.Objects.ObjectParameter("Pi_IdCuenta", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Portal_ComprobanteResumenPDF_Result>("P_Portal_ComprobanteResumenPDF", pi_IdPagoParameter, pi_IdCuentaParameter);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<P_Portal_ComprobanteResumenPDFHistorico_Result> P_Portal_ComprobanteResumenPDFHistorico(Nullable<long> pi_IdPago, Nullable<long> pi_IdCuenta)
        {
            var pi_IdPagoParameter = pi_IdPago.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("Pi_IdPago", pi_IdPago) :
                new System.Data.Entity.Core.Objects.ObjectParameter("Pi_IdPago", typeof(long));
    
            var pi_IdCuentaParameter = pi_IdCuenta.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("Pi_IdCuenta", pi_IdCuenta) :
                new System.Data.Entity.Core.Objects.ObjectParameter("Pi_IdCuenta", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Portal_ComprobanteResumenPDFHistorico_Result>("P_Portal_ComprobanteResumenPDFHistorico", pi_IdPagoParameter, pi_IdCuentaParameter);
        }
    }
}
