//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public Pago()
        {
            this.IntentoPago = new HashSet<IntentoPago>();
            this.PagoDetalleBoleta = new HashSet<PagoDetalleBoleta>();
        }
    
        public long IdPago { get; set; }
        public long IdConsultaBoleta { get; set; }
        public Nullable<long> CodigoTbk { get; set; }
        public Nullable<System.DateTime> FechaContable { get; set; }
        public Nullable<int> FolioXCash { get; set; }
        public string TicketXCash { get; set; }
        public string Cub { get; set; }
        public int IdEstadoPago { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<System.DateTime> FechaRegistroNotificacion { get; set; }
        public string TbkToken { get; set; }
        public Nullable<int> IdTipoMP { get; set; }
        public string FechaPagoString { get; set; }
    
        public virtual ConsultaBoleta ConsultaBoleta { get; set; }
        public virtual EstadoPago EstadoPago { get; set; }
        public virtual ICollection<IntentoPago> IntentoPago { get; set; }
        public virtual ICollection<PagoDetalleBoleta> PagoDetalleBoleta { get; set; }
    }
}
