//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promociones
    {
        public int Id { get; set; }
        public int IdPromocion { get; set; }
        public string Titulo { get; set; }
        public string Contenido { get; set; }
        public string Link { get; set; }
        public string NombreLink { get; set; }
        public Nullable<bool> PermiteLink { get; set; }
        public Nullable<bool> PermiteBases { get; set; }
        public string TextoBases { get; set; }
        public string NombreBases { get; set; }
        public byte[] Bases { get; set; }
        public string NombreLogo { get; set; }
        public byte[] Logo { get; set; }
        public string NombrePromocion { get; set; }
        public byte[] Promocion { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
