//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminoCondicion
    {
        public TerminoCondicion()
        {
            this.Cliente = new HashSet<Cliente>();
        }
    
        public int IdTermino { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public string UrlTerminoCondicion { get; set; }
        public Nullable<System.DateTime> FechaIngresoTermino { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual EstadoGeneral EstadoGeneral { get; set; }
    }
}
