//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoMail
    {
        public TipoMail()
        {
            this.CuerpoMail = new HashSet<CuerpoMail>();
            this.Mailing = new HashSet<Mailing>();
        }
    
        public int IdTipoMail { get; set; }
        public string DescTipoMail { get; set; }
        public int IdEstado { get; set; }
    
        public virtual ICollection<CuerpoMail> CuerpoMail { get; set; }
        public virtual EstadoGeneral EstadoGeneral { get; set; }
        public virtual ICollection<Mailing> Mailing { get; set; }
    }
}
