//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public Turno()
        {
            this.PagoDetalleBoleta = new HashSet<PagoDetalleBoleta>();
        }
    
        public string IdTurno { get; set; }
        public System.DateTime FechaCierreTurno { get; set; }
        public int IdEstado { get; set; }
        public int IdCanal { get; set; }
    
        public virtual EstadoGeneral EstadoGeneral { get; set; }
        public virtual ICollection<PagoDetalleBoleta> PagoDetalleBoleta { get; set; }
    }
}
