//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Profiles = new HashSet<Profiles>();
        }
    
        public string UserName { get; set; }
        public string Password { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime LastActivity { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastPasswordDate { get; set; }
        public Nullable<int> FailedPasswordAttempCount { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<Profiles> Profiles { get; set; }
    }
}
