//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.IntentoUsuario = new HashSet<IntentoUsuario>();
        }
    
        public int IdUsuario { get; set; }
        public int RutUsuario { get; set; }
        public string DvUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string PasswordUsuario { get; set; }
        public string EmailUsuario { get; set; }
    
        public virtual ICollection<IntentoUsuario> IntentoUsuario { get; set; }
    }
}
