//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtributoInformar
    {
        public AtributoInformar()
        {
            this.CodigoEmpresaInformar = new HashSet<CodigoEmpresaInformar>();
        }
    
        public long IdAtributoInformar { get; set; }
        public string NombreAtributo { get; set; }
        public string CodigoAtributo { get; set; }
        public string TipoMetadato { get; set; }
        public Nullable<int> Largo { get; set; }
        public int IdEmpresaRubro { get; set; }
        public Nullable<int> posicion { get; set; }
        public Nullable<bool> estado { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual ICollection<CodigoEmpresaInformar> CodigoEmpresaInformar { get; set; }
        public virtual EmpresaRubro EmpresaRubro { get; set; }
    }
}
