//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canal
    {
        public Canal()
        {
            this.ConfiguracionCanal = new HashSet<ConfiguracionCanal>();
            this.URLPermitidaCanal = new HashSet<URLPermitidaCanal>();
            this.RestriccionEPSCanal = new HashSet<RestriccionEPSCanal>();
            this.MedioPago = new HashSet<MedioPago>();
        }
    
        public int IdCanal { get; set; }
        public int IdEstado { get; set; }
        public string NombreCanal { get; set; }
        public string IdExterno { get; set; }
        public string CanalXCash { get; set; }
        public string TerminalXCash { get; set; }
        public Nullable<int> IdSucursal { get; set; }
    
        public virtual EstadoGeneral EstadoGeneral { get; set; }
        public virtual ICollection<ConfiguracionCanal> ConfiguracionCanal { get; set; }
        public virtual ICollection<URLPermitidaCanal> URLPermitidaCanal { get; set; }
        public virtual ICollection<RestriccionEPSCanal> RestriccionEPSCanal { get; set; }
        public virtual ICollection<MedioPago> MedioPago { get; set; }
    }
}
