//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comuna
    {
        public Comuna()
        {
            this.Direccion = new HashSet<Direccion>();
            this.Sucursal = new HashSet<Sucursal>();
        }
    
        public int IdComuna { get; set; }
        public int IdProvincia { get; set; }
        public string NombreComuna { get; set; }
    
        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<Direccion> Direccion { get; set; }
        public virtual ICollection<Sucursal> Sucursal { get; set; }
    }
}
