//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigVisualMantenedorPopUp
    {
        public long IdConfigVisual { get; set; }
        public string NombreImagen { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<long> NumeroImagen { get; set; }
        public string Url { get; set; }
        public string TargetPag { get; set; }
        public int IdConfig { get; set; }
    
        public virtual ConfigMantenedorPopUp ConfigMantenedorPopUp { get; set; }
    }
}
