//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigMantenedorPopUp
    {
        public ConfigMantenedorPopUp()
        {
            this.ConfigVisualMantenedorPopUp = new HashSet<ConfigVisualMantenedorPopUp>();
        }
    
        public int IdConfig { get; set; }
        public int IdTipoAmbiente { get; set; }
        public long Periodo { get; set; }
        public bool Habilitado { get; set; }
        public long TiempoRotacion { get; set; }
    
        public virtual ICollection<ConfigVisualMantenedorPopUp> ConfigVisualMantenedorPopUp { get; set; }
    }
}
