//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaProcesoConsulta
    {
        public int IdCuentaProcesoConsulta { get; set; }
        public long IdProcesoConsulta { get; set; }
        public int IdCuentaCliente { get; set; }
        public string CodigoInstrumento { get; set; }
        public string NombreIdentificador { get; set; }
        public string TipoMetaDato { get; set; }
        public string Identificador { get; set; }
        public string MapaFechaVencimiento { get; set; }
        public string CampoAfectado { get; set; }
        public Nullable<bool> EsRua { get; set; }
        public Nullable<int> TipoConsulta { get; set; }
        public Nullable<int> IdEstadoConsulta { get; set; }
    
        public virtual ConfiguracionProcesoConsulta ConfiguracionProcesoConsulta { get; set; }
        public virtual CuentaCliente CuentaCliente { get; set; }
    }
}
