//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaConsultada
    {
        public long idCuentaConsultada { get; set; }
        public Nullable<long> idConfiguracion { get; set; }
        public long idCuentaCliente { get; set; }
        public Nullable<System.DateTime> fechaVencimiento { get; set; }
        public Nullable<int> montoAdeudado { get; set; }
        public Nullable<long> idcliente { get; set; }
        public Nullable<bool> rua { get; set; }
        public Nullable<bool> pagoAgrupado { get; set; }
        public string CampoAgrupado { get; set; }
        public Nullable<int> numeroCuota { get; set; }
        public Nullable<int> idCuentaRua { get; set; }
        public Nullable<int> idEstadoConsulta { get; set; }
        public Nullable<System.DateTime> FechaInicioConsulta { get; set; }
        public Nullable<System.DateTime> FechaRespuestaConsulta { get; set; }
        public string codigoRespuesta { get; set; }
        public string observacionConsutla { get; set; }
    
        public virtual ConfiguracionProcesoConsulta ConfiguracionProcesoConsulta { get; set; }
    }
}
