//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuerpoMail
    {
        public int IdTipoMail { get; set; }
        public int Correlativo { get; set; }
        public string CuerpoHtmlMail { get; set; }
    
        public virtual TipoMail TipoMail { get; set; }
    }
}
