//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCuenta
    {
        public DetalleCuenta()
        {
            this.CampoOrdenConsulta = new HashSet<CampoOrdenConsulta>();
            this.CodigoEmpresaImprimir = new HashSet<CodigoEmpresaImprimir>();
            this.CodigoEmpresaInformar = new HashSet<CodigoEmpresaInformar>();
            this.PagoDetalleBoleta = new HashSet<PagoDetalleBoleta>();
        }
    
        public long IdDetalleCuenta { get; set; }
        public long IdCuenta { get; set; }
        public string FechaVctoCuenta { get; set; }
        public long MontoCuenta { get; set; }
        public string NumeroDocumento { get; set; }
        public Nullable<int> NumeroCuota { get; set; }
        public Nullable<System.DateTime> FechaInicioValidacion { get; set; }
        public Nullable<System.DateTime> FechaFinValidacion { get; set; }
    
        public virtual AtributoNoLlave AtributoNoLlave { get; set; }
        public virtual ICollection<CampoOrdenConsulta> CampoOrdenConsulta { get; set; }
        public virtual ICollection<CodigoEmpresaImprimir> CodigoEmpresaImprimir { get; set; }
        public virtual ICollection<CodigoEmpresaInformar> CodigoEmpresaInformar { get; set; }
        public virtual Cuenta Cuenta { get; set; }
        public virtual ICollection<PagoDetalleBoleta> PagoDetalleBoleta { get; set; }
    }
}
