//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaRubro
    {
        public EmpresaRubro()
        {
            this.AbonoDinamico = new HashSet<AbonoDinamico>();
            this.AtributoImprimir = new HashSet<AtributoImprimir>();
            this.AtributoInformar = new HashSet<AtributoInformar>();
            this.CuentaCliente = new HashSet<CuentaCliente>();
            this.CuentaClienteExpress = new HashSet<CuentaClienteExpress>();
            this.LinkAccesoPortal = new HashSet<LinkAccesoPortal>();
            this.LinkAccesoPortal1 = new HashSet<LinkAccesoPortal>();
            this.Identificador = new HashSet<Identificador>();
            this.ReglaPresentacion = new HashSet<ReglaPresentacion>();
            this.RestriccionEPSCanal = new HashSet<RestriccionEPSCanal>();
            this.MedioPago = new HashSet<MedioPago>();
        }
    
        public int IdEmpresaRubro { get; set; }
        public int IdEmpresa { get; set; }
        public int IdRubro { get; set; }
        public string NombreServicio { get; set; }
        public int IdEstado { get; set; }
        public bool CarteraDesconocida { get; set; }
        public bool AceptaAbono { get; set; }
        public string UrlLogoServicio { get; set; }
        public string CodigoInstrumento { get; set; }
        public string MapaFechaVencimiento { get; set; }
        public string CodigoTransbank { get; set; }
        public Nullable<bool> valida { get; set; }
        public string nombreBoton { get; set; }
        public int IdTipoAbono { get; set; }
        public int TipoConsulta { get; set; }
        public bool AceptaDeudaCero { get; set; }
        public Nullable<bool> Inscripcion { get; set; }
        public Nullable<bool> Express { get; set; }
    
        public virtual ICollection<AbonoDinamico> AbonoDinamico { get; set; }
        public virtual ICollection<AtributoImprimir> AtributoImprimir { get; set; }
        public virtual ICollection<AtributoInformar> AtributoInformar { get; set; }
        public virtual ICollection<CuentaCliente> CuentaCliente { get; set; }
        public virtual ICollection<CuentaClienteExpress> CuentaClienteExpress { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<LinkAccesoPortal> LinkAccesoPortal { get; set; }
        public virtual ICollection<LinkAccesoPortal> LinkAccesoPortal1 { get; set; }
        public virtual Rubro Rubro { get; set; }
        public virtual EstadoGeneral EstadoGeneral { get; set; }
        public virtual ICollection<Identificador> Identificador { get; set; }
        public virtual TipoAbono TipoAbono { get; set; }
        public virtual ICollection<ReglaPresentacion> ReglaPresentacion { get; set; }
        public virtual ICollection<RestriccionEPSCanal> RestriccionEPSCanal { get; set; }
        public virtual ICollection<MedioPago> MedioPago { get; set; }
    }
}
