//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.EmpresaRubro = new HashSet<EmpresaRubro>();
        }
    
        public int IdEmpresa { get; set; }
        public string CodEmpresa { get; set; }
        public int IdEstado { get; set; }
        public string NombreEmpresa { get; set; }
    
        public virtual EstadoGeneral EstadoGeneral { get; set; }
        public virtual ICollection<EmpresaRubro> EmpresaRubro { get; set; }
    }
}
