//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoGeneral
    {
        public EstadoGeneral()
        {
            this.Canal = new HashSet<Canal>();
            this.Empresa = new HashSet<Empresa>();
            this.EmpresaRubro = new HashSet<EmpresaRubro>();
            this.Turno = new HashSet<Turno>();
            this.Grupo = new HashSet<Grupo>();
            this.MedioPago = new HashSet<MedioPago>();
            this.Rubro = new HashSet<Rubro>();
            this.Sucursal = new HashSet<Sucursal>();
            this.TerminoCondicion = new HashSet<TerminoCondicion>();
            this.TipoMail = new HashSet<TipoMail>();
        }
    
        public int IdEstado { get; set; }
        public string DescEstadoGeneral { get; set; }
    
        public virtual ICollection<Canal> Canal { get; set; }
        public virtual ICollection<Empresa> Empresa { get; set; }
        public virtual ICollection<EmpresaRubro> EmpresaRubro { get; set; }
        public virtual ICollection<Turno> Turno { get; set; }
        public virtual ICollection<Grupo> Grupo { get; set; }
        public virtual ICollection<MedioPago> MedioPago { get; set; }
        public virtual ICollection<Rubro> Rubro { get; set; }
        public virtual ICollection<Sucursal> Sucursal { get; set; }
        public virtual ICollection<TerminoCondicion> TerminoCondicion { get; set; }
        public virtual ICollection<TipoMail> TipoMail { get; set; }
    }
}
