//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoImagen
    {
        public EstadoImagen()
        {
            this.ImagenEstilo = new HashSet<ImagenEstilo>();
        }
    
        public int IdEstadoImagen { get; set; }
        public string DescEstadoImagen { get; set; }
    
        public virtual ICollection<ImagenEstilo> ImagenEstilo { get; set; }
    }
}
