//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoMail
    {
        public EstadoMail()
        {
            this.Mailing = new HashSet<Mailing>();
        }
    
        public int IdEstadoMail { get; set; }
        public string DescEstadoMail { get; set; }
    
        public virtual ICollection<Mailing> Mailing { get; set; }
    }
}
