//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        public Grupo()
        {
            this.CuentaCliente = new HashSet<CuentaCliente>();
            this.ImagenEstilo = new HashSet<ImagenEstilo>();
        }
    
        public int IdGrupo { get; set; }
        public int IdEstado { get; set; }
        public string NombreGrupo { get; set; }
        public Nullable<long> IdCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<CuentaCliente> CuentaCliente { get; set; }
        public virtual EstadoGeneral EstadoGeneral { get; set; }
        public virtual ICollection<ImagenEstilo> ImagenEstilo { get; set; }
    }
}
