//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identificador
    {
        public Identificador()
        {
            this.IdentificadorCtaCli = new HashSet<IdentificadorCtaCli>();
            this.IdentificadorCtaCliExpress = new HashSet<IdentificadorCtaCliExpress>();
        }
    
        public int IdIdentificador { get; set; }
        public int IdEmpresaRubro { get; set; }
        public string DescIdentificador { get; set; }
        public string NombreIdentificador { get; set; }
        public string EjemploIdentificador { get; set; }
        public short LargoIdentificador { get; set; }
        public string UrlImagenIdentificador { get; set; }
        public int IdTipoMetaDato { get; set; }
        public Nullable<bool> IdentificadorHabilitado { get; set; }
    
        public virtual EmpresaRubro EmpresaRubro { get; set; }
        public virtual ICollection<IdentificadorCtaCli> IdentificadorCtaCli { get; set; }
        public virtual TipoMetaDato TipoMetaDato { get; set; }
        public virtual ICollection<IdentificadorCtaCliExpress> IdentificadorCtaCliExpress { get; set; }
    }
}
