//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntentoCliente
    {
        public long IdIntento { get; set; }
        public long IdCliente { get; set; }
        public string IpIntento { get; set; }
        public System.DateTime FechaIntento { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
