//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkAccesoPortal
    {
        public long IdLink { get; set; }
        public Nullable<int> IdEmpresaRubro { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaTermino { get; set; }
        public Nullable<bool> valido { get; set; }
        public string LinkEncriptado { get; set; }
    
        public virtual EmpresaRubro EmpresaRubro { get; set; }
        public virtual EmpresaRubro EmpresaRubro1 { get; set; }
    }
}
