//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mailing
    {
        public int id_mail { get; set; }
        public int id_tipo_mail { get; set; }
        public string mail_to { get; set; }
        public System.DateTime fecha_solicitud { get; set; }
        public Nullable<int> id_agente_mail { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public short id_estado_mail { get; set; }
        public string mail_llave_externa { get; set; }
        public Nullable<int> retorno_server_mail { get; set; }
    }
}
