//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailingAgentes
    {
        public string agente_mail { get; set; }
        public short id_agente_mail { get; set; }
        public System.DateTime fecha_ultimo_reporte { get; set; }
        public string agente_mail_estado { get; set; }
    }
}
