//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailingTipoDetalle
    {
        public int id_tipo_mail { get; set; }
        public short id_seccion_mail { get; set; }
        public short id_linea { get; set; }
        public string linea_mail { get; set; }
    }
}
