//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedioPago
    {
        public MedioPago()
        {
            this.IntentoPago = new HashSet<IntentoPago>();
            this.Canal = new HashSet<Canal>();
            this.EmpresaRubro = new HashSet<EmpresaRubro>();
        }
    
        public int IdMedioPago { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public string NombreMedioPago { get; set; }
        public Nullable<int> Id_tipoMedioPago { get; set; }
    
        public virtual EstadoGeneral EstadoGeneral { get; set; }
        public virtual ICollection<IntentoPago> IntentoPago { get; set; }
        public virtual Tipo_MedioPago Tipo_MedioPago { get; set; }
        public virtual ICollection<Canal> Canal { get; set; }
        public virtual ICollection<EmpresaRubro> EmpresaRubro { get; set; }
    }
}
