//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacion
    {
        public long IdNotificacion { get; set; }
        public Nullable<long> IdPagoDetalle { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaNotificacion { get; set; }
        public int IdEstadoNotificacion { get; set; }
        public Nullable<int> NumIntento { get; set; }
        public Nullable<bool> Habilitado { get; set; }
    
        public virtual EstadoNotificacion EstadoNotificacion { get; set; }
        public virtual PagoDetalleBoleta PagoDetalleBoleta { get; set; }
    }
}
