//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoDetalleBoleta
    {
        public PagoDetalleBoleta()
        {
            this.Notificacion = new HashSet<Notificacion>();
        }
    
        public long IdPagoDetalle { get; set; }
        public long IdDetalleCuenta { get; set; }
        public long IdPago { get; set; }
        public string IdTurno { get; set; }
        public string TbkTipoPago { get; set; }
        public Nullable<int> TbkNumCuota { get; set; }
        public string TbkCodAutoriza { get; set; }
        public Nullable<int> TbkNumTarjeta { get; set; }
        public string TbkIdTrx { get; set; }
        public Nullable<long> MontoPagado { get; set; }
        public int IdEstadoPago { get; set; }
        public Nullable<long> IdIntentoPago { get; set; }
        public Nullable<long> TbkMontoCuota { get; set; }
        public Nullable<int> TbkCodRespuesta { get; set; }
        public string TbkMontoTienda { get; set; }
        public string TipoPago { get; set; }
        public Nullable<int> Notificado { get; set; }
    
        public virtual DetalleCuenta DetalleCuenta { get; set; }
        public virtual EstadoPago EstadoPago { get; set; }
        public virtual ICollection<Notificacion> Notificacion { get; set; }
        public virtual Pago Pago { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
