//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrosConsulta
    {
        public long IdParametrosConsulta { get; set; }
        public long IdConsultaBoleta { get; set; }
        public string UrlExito { get; set; }
        public string UrlFracaso { get; set; }
        public string IdTransaccionExterna { get; set; }
        public string IdTicketEncriptado { get; set; }
        public Nullable<System.DateTime> FechaDespliegue { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<bool> Pagado { get; set; }
        public Nullable<bool> Procesado { get; set; }
        public Nullable<bool> Notificado { get; set; }
        public Nullable<System.DateTime> FechaNotificacion { get; set; }
    
        public virtual ConsultaBoleta ConsultaBoleta { get; set; }
    }
}
