//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReglaPresentacion
    {
        public int IdRegla { get; set; }
        public int IdEmpresaRubro { get; set; }
        public int IdTipoCartera { get; set; }
        public string CampoAfectado { get; set; }
        public string NombreCampoAfectado { get; set; }
    
        public virtual EmpresaRubro EmpresaRubro { get; set; }
        public virtual TipoCartera TipoCartera { get; set; }
    }
}
