//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumenPago
    {
        public long IdPago { get; set; }
        public System.DateTime FechaInserción { get; set; }
        public System.DateTime FechaPago { get; set; }
        public System.DateTime FechaContable { get; set; }
        public Nullable<long> Folio { get; set; }
        public string Ticket { get; set; }
        public string MedioPago { get; set; }
        public string DescripcionMedioPago { get; set; }
        public int Canal { get; set; }
        public bool Web { get; set; }
        public Nullable<bool> MailEnviado { get; set; }
        public Nullable<System.DateTime> FechaEnvioMail { get; set; }
        public long IdCliente { get; set; }
        public string Rut { get; set; }
        public string dv { get; set; }
        public bool Registrado { get; set; }
        public string Email { get; set; }
        public string NombreCliente { get; set; }
        public int MontoPago { get; set; }
        public Nullable<long> idConsultaBoleta { get; set; }
        public Nullable<int> EstadoPago { get; set; }
        public string DescripcionEstadoPago { get; set; }
        public string Cub { get; set; }
        public string Turno { get; set; }
    }
}
