//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCartera
    {
        public TipoCartera()
        {
            this.ReglaPresentacion = new HashSet<ReglaPresentacion>();
        }
    
        public int IdTipoCartera { get; set; }
        public string DescTipoCartera { get; set; }
    
        public virtual ICollection<ReglaPresentacion> ReglaPresentacion { get; set; }
    }
}
