//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zona
    {
        public Zona()
        {
            this.Sucursal = new HashSet<Sucursal>();
        }
    
        public int IdZona { get; set; }
        public string DescZona { get; set; }
    
        public virtual ICollection<Sucursal> Sucursal { get; set; }
    }
}
